export { AnimatedBackground } from './AnimatedBackground'
export { Navigation } from './Navigation'
export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { ExperienceSection } from './ExperienceSection'
export { SkillsSection } from './SkillsSection'
export { ProjectsSection } from './ProjectsSection'
export { ContactSection } from './ContactSection'
export { Footer } from './Footer'
export { TechBadge, techStacks } from './TechBadge'